"""PaperClaw Context Engineering package.

The package owns structured Context contracts, persistence, deterministic
selection/compaction, safe resume, and the opt-in v0.08 orchestration layer.
It does not own QueryEngine lifecycle or Tool permissions.
"""

from paperclaw.context.builder import (
    ContextBudgetExhausted,
    ContextBuilder,
    ContextBuilderError,
    EXCLUSION_BUDGET,
    EXCLUSION_CONFLICT,
    EXCLUSION_DEDUPLICATION,
    EXCLUSION_EXPIRED,
    EXCLUSION_SCOPE,
    EXCLUSION_SUPERSEDED,
    EXCLUSION_TRUST_VIOLATION,
    ROLE_COORDINATOR,
    ROLE_REVIEWER,
    ROLE_WORKER,
    RoleContextView,
)
from paperclaw.context.compaction import (
    Char4TokenEstimator,
    CompactionOutcome,
    CompactionPolicy,
    DEFAULT_ESTIMATOR,
    ESTIMATOR_CHAR4,
    TokenEstimator,
)
from paperclaw.context.contracts import (
    Checkpoint,
    CompactionResult,
    ContextBudget,
    ContextItem,
    ContextSnapshot,
    ContextSource,
    SessionEvent,
)
from paperclaw.context.migrations import MigrationRunner, SCHEMA_VERSION_V1
from paperclaw.context.orchestration import (
    ContextAssemblyBudgetExhausted,
    ContextAssemblyError,
    ContextAssemblyTrace,
    ContextBudgetAllocation,
    ContextCandidate,
    ContextCandidateSource,
    ContextConflict,
    ContextOrchestrator,
    ContextPolicy,
    ContextRequest,
    ContextSelection,
    PromptAssembler,
    PromptAssembly,
    PromptSection,
)
from paperclaw.context.repository import Repository, SQLiteRepository
from paperclaw.context.session import (
    EventSink,
    NullEventSink,
    SessionService,
    SqliteEventSink,
    open_session,
    reopen_session,
)

__all__ = [
    "Char4TokenEstimator",
    "Checkpoint",
    "CompactionOutcome",
    "CompactionPolicy",
    "CompactionResult",
    "ContextAssemblyBudgetExhausted",
    "ContextAssemblyError",
    "ContextAssemblyTrace",
    "ContextBudget",
    "ContextBudgetAllocation",
    "ContextBudgetExhausted",
    "ContextBuilder",
    "ContextBuilderError",
    "ContextCandidate",
    "ContextCandidateSource",
    "ContextConflict",
    "ContextItem",
    "ContextOrchestrator",
    "ContextPolicy",
    "ContextRequest",
    "ContextSelection",
    "ContextSnapshot",
    "ContextSource",
    "DEFAULT_ESTIMATOR",
    "ESTIMATOR_CHAR4",
    "EventSink",
    "EXCLUSION_BUDGET",
    "EXCLUSION_CONFLICT",
    "EXCLUSION_DEDUPLICATION",
    "EXCLUSION_EXPIRED",
    "EXCLUSION_SCOPE",
    "EXCLUSION_SUPERSEDED",
    "EXCLUSION_TRUST_VIOLATION",
    "MigrationRunner",
    "NullEventSink",
    "PromptAssembler",
    "PromptAssembly",
    "PromptSection",
    "ROLE_COORDINATOR",
    "ROLE_REVIEWER",
    "ROLE_WORKER",
    "Repository",
    "RoleContextView",
    "SCHEMA_VERSION_V1",
    "SQLiteRepository",
    "SessionEvent",
    "SessionService",
    "SqliteEventSink",
    "TokenEstimator",
    "open_session",
    "reopen_session",
]
