"""PaperClaw local retrieval, grounding and hybrid ranking foundation."""

from paperclaw.retrieval.chunking import build_chunks
from paperclaw.retrieval.context_source import (
    CitationAnchor,
    RetrievalContextSource,
    RetrievalGroundingDecision,
    RetrievalGroundingPolicy,
    extract_retrieval_query,
    register_retrieval_context_source,
)
from paperclaw.retrieval.contracts import (
    BlockLocator,
    Chunk,
    ChunkConfig,
    ChunkLocator,
    DocumentIdentity,
    DocumentVersion,
    IndexManifest,
    ParsedBlock,
    RegistryMutationResult,
    SourceArtifact,
    canonical_json,
    compute_corpus_hash,
    sha256_bytes,
    sha256_text,
    stable_id,
)
from paperclaw.retrieval.evaluation import (
    RetrievalJudgment,
    RetrievalMetrics,
    evaluate_judgment,
    evaluate_suite,
    ndcg_at_k,
    recall_at_k,
    reciprocal_rank,
)
from paperclaw.retrieval.grounding import (
    GroundingClaimJudgment,
    GroundingMetrics,
    cited_anchor_ids,
    evaluate_grounding,
)
from paperclaw.retrieval.hybrid import (
    HybridCorpusMismatchError,
    HybridRetriever,
    Retriever,
    hybrid_configuration_fingerprint,
)
from paperclaw.retrieval.incremental import IncrementalIndexer, IncrementalIndexResult
from paperclaw.retrieval.integrity import (
    IndexIntegrityReport,
    IndexRebuildResult,
    SQLiteIndexMaintainer,
)
from paperclaw.retrieval.parsers import MarkdownParser, ParserOutput, PlainTextParser, select_parser
from paperclaw.retrieval.query import (
    BrokenIndexError,
    RankedResult,
    RetrievalCandidate,
    RetrievalError,
    RetrievalRequest,
    SQLiteBM25Retriever,
    StaleIndexError,
    retrieved_ids,
)
from paperclaw.retrieval.registry import SQLiteDocumentRegistry

__all__ = [
    "BlockLocator",
    "BrokenIndexError",
    "Chunk",
    "ChunkConfig",
    "ChunkLocator",
    "CitationAnchor",
    "DocumentIdentity",
    "DocumentVersion",
    "GroundingClaimJudgment",
    "GroundingMetrics",
    "HybridCorpusMismatchError",
    "HybridRetriever",
    "IncrementalIndexer",
    "IncrementalIndexResult",
    "IndexIntegrityReport",
    "IndexManifest",
    "IndexRebuildResult",
    "MarkdownParser",
    "ParsedBlock",
    "ParserOutput",
    "PlainTextParser",
    "RankedResult",
    "RegistryMutationResult",
    "Retriever",
    "RetrievalCandidate",
    "RetrievalContextSource",
    "RetrievalError",
    "RetrievalGroundingDecision",
    "RetrievalGroundingPolicy",
    "RetrievalJudgment",
    "RetrievalMetrics",
    "RetrievalRequest",
    "SQLiteBM25Retriever",
    "SQLiteDocumentRegistry",
    "SQLiteIndexMaintainer",
    "SourceArtifact",
    "StaleIndexError",
    "build_chunks",
    "canonical_json",
    "cited_anchor_ids",
    "compute_corpus_hash",
    "evaluate_grounding",
    "evaluate_judgment",
    "evaluate_suite",
    "extract_retrieval_query",
    "hybrid_configuration_fingerprint",
    "ndcg_at_k",
    "recall_at_k",
    "reciprocal_rank",
    "register_retrieval_context_source",
    "retrieved_ids",
    "select_parser",
    "sha256_bytes",
    "sha256_text",
    "stable_id",
]
